### ISSUE TITLE
email-to-slack - Edits for PHP 5.3.9?

### ISSUE THREAD

**Issue by tonywilson** [mehdichaouch/email-to-slack#1]
We're running an older scripting server that unfortunately only has PHP v5.3.9 installed.  I've been attempting to retool the email-to-slack script to run on our older version of PHP (removing http_response_code commands and replacing [] with array()), but have been unable to get the script to move any incoming messages on our Slack group.  As a newbie to JSON, I'm not sure some of these calls may also be unavailable in older versions of PHP.  Can you offer any advice?

**Comment by mehdichaouch** [comment]
To help you with your PHP 5.3.9 use case, I installed PHP Compatibility to Github CI, like that you can see an exhaustive list of PHP things that need to be refactored [runs/3051084186](https://github.com/mehdichaouch/email-to-slack/runs/3051084186?check_suite_focus=true#step:7:8). I hope this will help.

**Comment by tonywilson** [comment]
Mehdi,

 

                That’s very nice of you – thanks!  It looks like compatibility issues you’re seeing are those that I’ve addressed in my edited code.  I’ve run a compatibility check on my modified code following your lead, and am receiving a clean bill of health.  Unfortunately, as the installed script doesn’t generate any error logs on Slack (at least as modified), its currently not possible to see (1) whether it is activating when a new message comes in and (2) if so, why the incoming message is not rerouted.   Is there some way that I can test the code with a sample email to see if its doing what it should or a way to make Slack provide more verbose output from the bot?

 

Sorry for my confusion – I feel I’ve gone down a rabbit hole here…

 

Tony

**Comment by mehdichaouch** [comment]
Hello @tonywilson,

Did you found a solution? If you need I can share with you a version of the script with some debugging lines (`file_put_contents`). Let me know.

Lastly, if the script need some adaptation for PHP 5.3, if you what you can share those on a branch named `PHP5.3`.

**Comment by tonywilson** [comment]
Medhi,

 

                No, I wasn’t able to get the Slack script to work.  I ended up using a Google script to accomplish the task, and it seems to be running without any problems.

 

https://gist.github.com/rushimusmaximus/bcb847b89457b6936d50

 

Thanks for your help,


Tony

**Comment by mehdichaouch** [comment]
@tonywilson ok, so I close this issue.
Thanks for the alternative : https://gist.github.com/rushimusmaximus/bcb847b89457b6936d50 😉
